# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 10.0
      # - M1_TO_LINK0
      # - M10_TO_LINK1
      # - M3_TO_LINK10
      # - M4_TO_LINK3
      # - M5_TO_LINK4
M5_TO_LINK4:
  ID: 5
  Return_Delay_Time: 0
  Operating_Mode: 3
  Goal_Velocity: 10
  Profile_Acceleration: 10
  Profile_Velocity: 10
M4_TO_LINK3:
  ID: 4
  Return_Delay_Time: 0
  Operating_Mode: 3
  Goal_Velocity: 10
  Profile_Acceleration: 10
  Profile_Velocity: 10
M3_TO_LINK2:
  ID: 3
  Return_Delay_Time: 0
  Operating_Mode: 3
  Goal_Velocity: 10
  Profile_Acceleration: 10
  Profile_Velocity: 10
M2_TO_LINK1:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 3
  Goal_Velocity: 10
  Profile_Acceleration: 10
  Profile_Velocity: 10
M1_TO_LINK0:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 3
  Goal_Velocity: 10
  Profile_Acceleration: 10
  Profile_Velocity: 10
